# [](#1BA6FA)\
# $directory\
# [](fg:#1BA6FA bg:#FBA300)\
# $git_branch\
# $git_status\
# [](fg:#FBA300 bg:#69e228)\
# $nodejs\
# [](fg:#69e228)\
# [

# ](bold fg:#69e228)\

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
[>> ](bold fg:#7dcfff)\
"""

# [fill]
# symbol = ""
# style = ""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bold bg:#69e228 fg:#292C3E"
style_root = "bold bg:#69e228 fg:#292C3E"
format = '[$user ]($style)'

[directory]
style = "bold fg:#e0af68"
format = "[$path ]($style bold)"
truncation_length = 10
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📁"
"Downloads" = ""
"music" = ""
"Pictures" = ""
"projects" = ""
"web" = ""
"wrk" = ""
".hyprdots" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bold fg:#9ece6a"
format = '[$symbol $branch ]($style)'

[git_status]
style = "bold fg:#9ece6a"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bold fg:#69e228"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
